default:
  control_plane_url: "http://localhost:8080"
  kafka_bootstrap: "localhost:9092"
  prometheus_url: "http://localhost:9090"

docker:
  control_plane_url: "http://backend:8080"
  kafka_bootstrap: "kafka:9092"
  prometheus_url: "http://prometheus:9090"

ci:
  control_plane_url: "${CONTROL_PLANE_URL}"
  kafka_bootstrap: "${KAFKA_BOOTSTRAP}"
  prometheus_url: "${PROMETHEUS_URL}"
